title: martoc.github.io
description: >- # this means to ignore newlines until "baseurl:"
  Notes about AWS, K8s, AI and Data
url: "https://martoc.github.io"
github_username:  martoc
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num"

google_analytics: G-TRCR5NDSVF

# Build settings
theme: bulma-clean-theme
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  - scope:
      path: ""
      type: "posts"
    values:
      author: "martoc"
      layout: post
      show_sidebar: true