name: Push site

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 10
        fetch-tags: true
    - name: Tag
      uses: martoc/action-tag@v0
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:4.2.2 /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
    - name: Release on GitHub
      uses: martoc/action-release@v0
